---
driver:
  name: ec2
  aws_ssh_key_id: ec2-key
  associate_public_ip: true
  region: us-west-2
  availability_zone: a
  subnet_id: subnet-e424afad
  instance_type: t2.micro
  image_id: ami-0b7af46b
  security_group_ids: sg-853950fe
  retryable_tries: 120


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: authoring-ami
    transport:
      username: ec2-user
    driver:
      image_id: ami-0b7af46b
#    block_device_mappings:
      #- ebs_device_name: /dev/sdb
        #ebs_volume_type: gp2
        #ebs_virtual_name: test
        #ebs_volume_size: 8
        #ebs_delete_on_termination: true

transport:
  ssh_key: ~/Documents/ec2-key.pem

suites:
  - name: default
    attributes:
      secrets:
        kms_region: us-west-2
        secrets_s3_bucket: iss-206199558186-us-west-2
        kms_cmk_id: d5f0a34d-9be4-4992-a001-8ff022b2dafa
        shred_secrets: 'false'
        cli_source: artifacts-206199558186-us-west-2
        cli_package: secrets-cli-2.3.4.0.rpm
    run_list:
      - recipe[authoring::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
