---
driver:
  name: ec2
  aws_ssh_key_id: ec2-key
  associate_public_ip: true
  region: us-west-2
  availability_zone: a
  subnet_id: subnet-e424afad
  instance_type: t2.micro
  image_id: ami-3e96f15e
  security_group_ids: sg-853950fe
  retryable_tries: 120


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    transport:
      username: ec2-user
    driver:
      image_id: ami-3e96f15e
#    block_device_mappings:
      #- ebs_device_name: /dev/sdb
        #ebs_volume_type: gp2
        #ebs_virtual_name: test
        #ebs_volume_size: 8
        #ebs_delete_on_termination: true

transport:
  ssh_key: ~/Documents/ec2-key.pem

suites:
  - name: default
    run_list:
      - recipe[authoring::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
